[displayconfig]
# #########################################################
work = "repeatblocks_5"
# work = diagnostics
isrpi = false
rendering = "hub"
rotation = 0
fullrotation = true
rotationtrailing = false
checkforconfigchanges = true
dofullreloadonchange = true
tilesizeheight = 40
tilesizewidth = 80
matrixtiles = 48
rows = 8
cols = 4
# ---  Also determines the window geometry
screenwidth = 512
screenheight = 256
# ---  preparing for rotation
windowwidth = 512
windowheight = 256
canvaswidth = 512
canvasheight = 256
# - for small adjustments when sending to
# - matrix panels & cards
canvasoffsetx = 3
canvasoffsety = 3
# Window Offset
# windowXOffset = 2647
windowxoffset = 2647
windowyoffset = 236
brightness = 1.0
minbrightness = 0
# work = squares
# rotation = 0
# screenWidth = 320
# screenHeight = 192
# canvasWidth = 320
# canvasHeight = 192
remapimageblock = false
remapimageblocksection = [0,0,64,384]
remapimageblockdestination = [0,0]
remapimageblocksectionrotation = 0
remapimageblock2 = false
remapimageblocksection2 = "0,220,160,256"
remapimageblockdestination2 = "1,220"
remapimageblocksection2rotation = 1
remapimageblock3 = false
remapimageblocksection3 = "224,0,256,384"
remapimageblockdestination3 = "0,0"
remapimageblocksection3rotation = 0
usepixelsort = false
pixelsortrotateswithimage = false
pixsortdirection = "lateral"
unsharpmaskpercent = 30
blurradius = 0
pixsortxoffset = 0
pixsortyoffset = -2.0
pixsortboxheight = 1
pixsortboxwidth = 192
pixsortgap = 0
pixsortprobdraw = 0.02
pixsortprobgetnextcolor = 1
pixsortprobdecriment = 0
pixsortsizedecriment = 0
pixsortsamplevariance = 12
pixsortdrawvariance = 1
randomcolorprobabilty = 0.001
brightnessvarlow = 0.9
brightnessvarhi = 1.1
pixelsortappearanceprob = 0.99
useblur = false
blurxoffset = 120
bluryoffset = 120
blursectionwidth = 90
blursectionheight = 20
sectionblurradius = 2
usefilters = true
ditherfilterbrightness = 1.1

[comboSet5]
# patterns = tripart,circles,gothic1,randomizer2,randomizer,waveScales,fishScales,wavePattern2,decoBoxes,reMove,concentricBoxes,diamond,balls,compass,logcabin,peaceCross
patterns = ["waveScales","fishScales","gothic2","compass","balls","circles","fishScales2","fishScales3","compass_hili","balls_hili"]
dominantpatterns = "fishScales3"
dominantpatternprob = 0.5
palettes = "deep2,oceansky,retrotest1"
# Border Controls
borderpattern = "compass"
useborderpattern = false
altcoloringprob = 0.9
poprandomcolorprob = 0.1
