import os
import shutil

filesToMove = ["library/patterns_scrolling_moving/movingbars.cfg",
"library/patterns_scrolling_moving/movingbars-bundle-version.cfg",
"library/patterns_scrolling_moving/large-triangle-movingbars_b.cfg",
"library/flame_and_particle_variants/p4-6x16_chimney.cfg",
"library/flame_and_particle_variants/p4-6x8_fireside.cfg",
"library/flame_and_particle_variants/img-hub1-recovery.cfg",
"library/p2.5-small-informal/actionmarks-1_2_init_config.cfg",
"library/p4-3x8-informal/spots.cfg",
"library/p4-3x8-informal/p4-3x7-quilt-stars.cfg",
"library/p4-3x8-informal/flag.cfg",
"library/p4-3x8-informal/spots2.cfg",
"library/p4-3x8-informal/square-polys.cfg",
"library/p4-3x8-informal/p4-3x7-quilt-triangles-b.cfg",
"library/to_be_resolved/pixel-shack-gradients-4x6.cfg",
"library/to_be_resolved/p4-3x8-informal_leaf-factory.cfg",
"library/to_be_resolved/present-b.cfg",
"library/to_be_resolved/optic.cfg",
"library/to_be_resolved/triangles_a.cfg",
"library/image_repeaters/movingpattern_b.cfg",
"library/image_repeaters/movingpattern.cfg",
"library/patterns_and_glitch_screens/barblocks-pattern-infomal.cfg",
"library/archive_p4-2x4/img-hub.cfg",
"library/archive_p4-2x4/fluddRPI.cfg",
"library/archive_p4-2x4/repaintRPI.cfg",
"library/archive_p4-2x4/marqueeRPI.cfg",
"library/archive_p4-2x4/square-polys.cfg",
"library/archive_p4-2x4/mono-flavin-RPI.cfg",
"library/archive_p4-2x4/quiltx.cfg",
"library/F22_workups/p4-40x80-spots3.cfg",
"library/F22_workups/industrial-incandescent-led-comp-spritesheet-2.cfg",
"library/F22_workups/spritesheet-1.cfg",
"library/F22_workups/p5-tilt-gap-spots2.cfg",
"library/planks_and_beams/particles.cfg",
"library/planks_and_beams/img-hub.cfg",
"library/planks_and_beams/img-hub-x2.cfg",
"library/planks_and_beams/img-hub-bak.cfg",
"library/planks_and_beams/branch-quilt-1.cfg",
"library/planks_and_beams/plank-movement-a.cfg",
"library/planks_and_beams/plank-gradients.cfg",
"library/quilts/p4-3x8-informal_quilt2a.cfg",
"library/quilts/p3-2x6-squares.cfg",
"library/quilts/p4-6x8_quilt-poly.cfg",
"library/quilts/p4-3x8-informal_quilt2b.cfg",
"library/quilts/p4-4x8_quilt-log-cabin.cfg",
"library/quilts/quilt-stars.cfg",
"library/quilts/p4-4x8_square-rug.cfg",
"library/quilts/quilt-log-cabin.cfg",
"library/quilts/quilt-triangles.cfg",
"library/quilts/quilt-polys.cfg",
"library/quilts/p4-3x8-informal_quilt.cfg",
"library/quilts/p3-2x6_quilt_triangles.cfg",
"library/quilts/quilt-informal.cfg",
"library/quilts/p4-6x8_quilt-stars.cfg",
"library/quilts/l-quilt.cfg",
"library/quilts/p4-3x8-informal_quilt-polys.cfg",
"library/quilts/p4-3x8-informal_quilt-squares.cfg",
"library/quilts/p4-3x8-informal_quilt-squares-plane.cfg",
"library/quilts/p4-3x8-informal_quilt-stars.cfg",
"library/quilts/quilt.cfg",
"library/quilts/p3-2x6-squares-b.cfg",
"library/quilts/quiltx.cfg",
"library/quilts/p4-3x8-informal_quilt-triangles-b.cfg",
"staging/landscaper-actionmarks-bundle/actionmarks-v2.cfg",
"staging/landscaper-actionmarks-bundle/actionmarks-v3-512.cfg",
"dev/forms/p4-256x384-large-informal/p4-256x384-quilt-disturbed-informal-logcabin.cfg",
"dev/forms/p4-256x384-large-informal/p4-256x384-quilt-disturbed-poly.cfg",
"dev/forms/p10-tower-t-shape/p10-tower-pflames-r-stonehenge-b.cfg",
"dev/forms/chimnys/p4-6x8-chimney-algofall9-b1c.cfg",
"dev/forms/p4-tower-40x80/p4-tower-ba_spritesheet_bbear.cfg",
"dev/forms/long-drape/algofall9-b1c.cfg",
"dev/forms/p2.5-aggregator/p4-firebox-flame-particles-v2.cfg",
"dev/forms/p2.5-aggregator/p4-firebox-spritesheet3-a.cfg",
"dev/forms/p4-p5-plank/p5-firebeams-particles_fire_algo-b-copy.cfg",
"dev/forms/p4-p5-plank/p5-firebeams-particles_fire_algo-a.cfg",
"dev/forms/draped/p4-draped-repeatblocks_5.cfg",
"dev/surface-structures-animations/repeatblock-patterns/p8-repeatblocks_2-flat_a.cfg",
"dev/surface-structures-animations/repeatblock-patterns/repeatblocks_2-flat_d.cfg",
"dev/surface-structures-animations/repeatblock-patterns/repeatblocks_2-flat_a.cfg",
"dev/surface-structures-animations/repeatblock-patterns/p2.5-128x704-repeatblocks.cfg",
"dev/surface-structures-animations/repeatblock-patterns/6x8v_repeatblocks_2-flat_b.cfg",
"dev/surface-structures-animations/repeatblock-patterns/p5-5x2_long_beams_repeatblocks_2.cfg",
"dev/surface-structures-animations/repeatblock-patterns/p5-tower-repeatblocks-v1.cfg",
"dev/surface-structures-animations/stroop/p2.5-long-adwords.cfg",
"dev/surface-structures-animations/stroop/p8-long-adwords.cfg",
"dev/surface-structures-animations/drawings_lines/drawing-192-x160.cfg",
"dev/surface-structures-animations/drawings_lines/p4-192x160-mile-line.cfg",
"dev/surface-structures-animations/drawings_lines/img-spritesheet-line.cfg",
"dev/surface-structures-animations/drawings_lines/drawing-line-192-x160.cfg",
"dev/surface-structures-animations/collaged_lights/p4-4x2-leaning-lights.cfg",
"dev/surface-structures-animations/voronoi/vornoi-glass.cfg",
"dev/surface-structures-animations/celestials/noise-scroller-test.cfg",
"dev/surface-structures-animations/celestials/p4-tower-particles_glory_v2b.cfg",
"dev/surface-structures-animations/celestials/noise-scroller-240x240.cfg",
"dev/surface-structures-animations/drawings_obear/ba-spritesheet-160-x160b.cfg",
"dev/surface-structures-animations/drawings_obear/ba-spritesheet-192-x160.cfg",
"dev/surface-structures-animations/flames-fires/p5-fire-spritesheet3.cfg",
"dev/surface-structures-animations/flames-fires/spritesheet-2-fireline.cfg",
"dev/surface-structures-animations/particles_moving/p5-propped-T-moving_points_5.cfg",
"dev/surface-structures-animations/particles_moving/p5-propped-T-moving_points_4.cfg",
"dev/surface-structures-animations/quilts/p4-4x7-slope-quilt-triangles.cfg",
"dev/surface-structures-animations/quilts/p4-quilt-test.cfg",
"dev/surface-structures-animations/quilts/p2.5-quilt-for-fla-poly.cfg",
"dev/surface-structures-animations/quilts/p4-40x80x3-tower-quilt.cfg",
"dev/surface-structures-animations/quilts/p4-4x7-slope-quilt-stars.cfg",
"dev/surface-structures-animations/quilts/test-quilt-for-fla-informal-logcabin.cfg",
"dev/surface-structures-animations/quilts/p2.5-quilt.cfg",
"dev/surface-structures-animations/quilts/p2.5-quilt-for-fla-triangles.cfg",
"dev/surface-structures-animations/quilts/p4-4x7-slope-quilt-triangles2.cfg",
"dev/surface-structures-animations/quilts/quilt-for-fla-informal-logcabin.cfg",
"dev/surface-structures-animations/quilts/p4-3x8-quilt-squares-plane.cfg",
"dev/in_progress_revisit/img_sq_player.cfg",
"dev/in_progress_revisit/flow-noise-distortion.cfg"]

fullPath = "/Users/lamshell/Documents/Dev/LEDELI/RPI/configs/"
newPath = "non_working/"
for _f in filesToMove :
    # print(fullPath + _f)

    fileNameParts = _f.split("/")
    fileName = ""
    for _part in fileNameParts :
        fileName += "_"+_part
    # print(fullPath + newPath + fileName)
    shutil.move(fullPath + _f, fullPath + newPath + fileName)
