path = "/home/pi/RPI"
MID = "RPI11"
MID = "studio-mac"
#WRKINID = "stroop-hub-1.2"
WRKINID = "stroop-hat-1.3-pi3"
#WRKINID = "machine-hub-1.1"
controlUrl = "http://192.168.1.124/projects/rpi-controls"