path = "/home/pi/RPI"
#path = "."
MID = "RPI9"
MID = "studio-mac"
#WRKINID = "stroop-hubout-1.0"
#WRKINID = "stroop2-hub-1.1"
WRKINID = "plane-hat-1.0"
controlUrl = "http://192.168.1.124/projects/rpi-controls"
